version: '3.8'

services:
  db:
    container_name: mariadb
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress:6.1.1-php8.2-fpm
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

  nginx:
      container_name: nginx
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      ports:
        - 443:443 #https 
      volumes:
        - wp_data:/var/www/html
      restart: always
      networks:
        - inception-network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/$USER/data/db
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/$USER/data/wp

networks:
  inception-network:
