services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
    volumes:
      - ~/data/db:/var/lib/mysql
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    image: wordpress
    # image: wordpress:6.1.1-php8.2-fpm
    volumes:
      - ~/data/wp:/var/www/html
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

  nginx:
      container_name: nginx
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      ports:
        - 443:443 #https 
      volumes:
        - ~/data/wp:/var/www/html
      restart: always
      networks:
        - inception-network

# volumes:
#   db_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /Users/$USER/data/db
#   wp_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /Users/$USER/data/wp

networks:
  inception-network:
