volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      device: ~/data/wp
      type: volume
      o: bind

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 443:443 #https 
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always
    networks:
      - inception-network
      
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
    volumes:
      - ~/data/db:/var/lib/mysql
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    image: wordpress
    # image: wordpress:6.1.1-php8.2-fpm
    volumes:
      - wordpress-volume:/var/www/wordpress
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

networks:
  inception-network:
